### ISSUE TITLE
Fazer FIR no MathLab ou em Python

### ISSUE THREAD

**Issue by sudjoao** [sudjoao/Projeto-PED1#1]
### **Tasks**:
- [ ] Criar um projeto do FIR no MathLab ou em Python para a próxima aula de PED.

**Comment by ErickGiffoni** [comment]
Na verdade essa issue consiste em implementar o somatório que representa a convolução de um sinal em uma certa frequência, com pesos arbitrários. Vide [apostila/projetos finais/projeto 5](https://aprender.ead.unb.br/pluginfile.php/372790/mod_resource/content/1/Apostila%20%28Material%20de%20Apoio%29.pdf)

**Comment by ErickGiffoni** [comment]
Implementado na branch ImplementarSomatorio
